# Generated by Django 5.2.1 on 2025-05-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(help_text='Zoom OAuth App Client ID', max_length=255)),
                ('client_secret', models.CharField(help_text='Zoom OAuth App Client Secret', max_length=255)),
                ('account_id', models.CharField(help_text='Zoom Account ID', max_length=255)),
                ('webinar_template_id', models.CharField(blank=True, help_text='Default Zoom Webinar Template ID (optional)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zoom Settings',
                'verbose_name_plural': 'Zoom Settings',
            },
        ),
    ]
