# Generated by Django 5.2.1 on 2025-05-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesforceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain', models.CharField(help_text="Salesforce instance subdomain (e.g., 'mycompany' for mycompany.salesforce.com)", max_length=255)),
                ('username', models.CharField(help_text='Salesforce username', max_length=255)),
                ('password', models.CharField(help_text='Salesforce password', max_length=255)),
                ('security_token', models.CharField(help_text='Salesforce security token', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Salesforce Settings',
                'verbose_name_plural': 'Salesforce Settings',
            },
        ),
    ]
