# Generated by Django 5.2.1 on 2025-06-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_salesforcesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MS365Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(help_text='Microsoft Azure App Client ID', max_length=255)),
                ('client_secret', models.CharField(help_text='Microsoft Azure App Client Secret', max_length=255)),
                ('tenant_id', models.CharField(help_text='Microsoft Azure Tenant ID', max_length=255)),
                ('owner_email', models.EmailField(help_text='Email address of the calendar owner (meetings will be created in this calendar)', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MS365 Settings',
                'verbose_name_plural': 'MS365 Settings',
            },
        ),
    ]
