# Generated by Django 5.2.1 on 2025-06-05 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_add_salesforce_oauth_fields'),
        ('settings', '0003_ms365settings'),
    ]

    operations = [
    ]
