# Generated by Django 5.2.1 on 2025-05-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='checkout_date_field',
            field=models.CharField(default='custom_field_getting_started_with_wordpress_dates', help_text='Field name in Kajabi checkout for date selection', max_length=255),
        ),
        migrations.AddField(
            model_name='webinar',
            name='error_notification_email',
            field=models.EmailField(default='info@awesometechtraining.com', help_text='Email to notify on webhook processing errors', max_length=254),
        ),
        migrations.AddField(
            model_name='webinar',
            name='form_date_field',
            field=models.CharField(default='Webinar options', help_text='Field name in Kajabi form for date selection', max_length=255),
        ),
    ]
