# Generated by Django 5.2.1 on 2025-05-29 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0002_webinar_checkout_date_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebinarBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('kajabi_grant_activation_hook_url', models.URLField(max_length=500)),
                ('form_date_field', models.CharField(default='Bundle options', help_text='Field name in Kajabi form for date selection', max_length=255)),
                ('checkout_date_field', models.CharField(default='custom_field_bundle_dates', help_text='Field name in Kajabi checkout for date selection', max_length=255)),
                ('error_notification_email', models.EmailField(default='info@awesometechtraining.com', help_text='Email to notify on webhook processing errors', max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BundleDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date_time', models.DateTimeField()),
                ('webinar_dates', models.ManyToManyField(related_name='bundle_dates', to='webinars.webinardate')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webinars.webinarbundle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BundleAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('bundle_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webinars.bundledate')),
            ],
            options={
                'unique_together': {('bundle_date', 'email')},
            },
        ),
    ]
