# Generated by Django 5.2.1 on 2025-06-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0004_change_bundledate_to_date_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='aliases',
            field=models.TextField(blank=True, help_text='Alternative names for this webinar (one per line). Used to match Kajabi offers/forms with different names.'),
        ),
        migrations.AddField(
            model_name='webinarbundle',
            name='aliases',
            field=models.TextField(blank=True, help_text='Alternative names for this bundle (one per line). Used to match Kajabi offers/forms with different names.'),
        ),
    ]
