# Generated by Django 5.2.1 on 2025-06-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0005_webinar_aliases_webinarbundle_aliases'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='activation_error',
            field=models.TextField(blank=True, help_text='Error message if activation failed'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='activation_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the Kajabi grant offer activation was sent', null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='activation_success',
            field=models.BooleanField(blank=True, help_text='Whether the activation was successful', null=True),
        ),
        migrations.AddField(
            model_name='bundleattendee',
            name='activation_error',
            field=models.TextField(blank=True, help_text='Error message if activation failed'),
        ),
        migrations.AddField(
            model_name='bundleattendee',
            name='activation_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the Kajabi grant offer activation was sent', null=True),
        ),
        migrations.AddField(
            model_name='bundleattendee',
            name='activation_success',
            field=models.BooleanField(blank=True, help_text='Whether the activation was successful', null=True),
        ),
    ]
