# Generated by Django 5.2.1 on 2025-06-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0006_attendee_activation_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinardate',
            name='calendar_invite_error',
            field=models.TextField(blank=True, help_text='Error message if calendar invite failed'),
        ),
        migrations.AddField(
            model_name='webinardate',
            name='calendar_invite_sent_at',
            field=models.DateTimeField(blank=True, help_text='When calendar invites were sent to staff', null=True),
        ),
        migrations.AddField(
            model_name='webinardate',
            name='calendar_invite_success',
            field=models.BooleanField(blank=True, help_text='Whether calendar invite sending was successful', null=True),
        ),
    ]
