# Generated by Django 5.2.1 on 2025-06-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0007_webinardate_calendar_invite_error_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=200)),
                ('headers', models.JSONField()),
                ('body', models.TextField(blank=True)),
                ('response_status', models.IntegerField()),
                ('response_body', models.TextField(blank=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='webinars_we_created_03df38_idx'), models.Index(fields=['success'], name='webinars_we_success_b1e240_idx')],
            },
        ),
    ]
