# Generated by Django 5.2.1 on 2025-06-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0008_webhooklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='zoom_join_url',
            field=models.URLField(blank=True, help_text='Personal Zoom join URL for this attendee', max_length=500),
        ),
        migrations.AddField(
            model_name='attendee',
            name='zoom_registered_at',
            field=models.DateTimeField(blank=True, help_text='When registered in Zoom', null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='zoom_registrant_id',
            field=models.CharField(blank=True, help_text='Zoom registrant ID if registered', max_length=100),
        ),
        migrations.AddField(
            model_name='attendee',
            name='zoom_registration_error',
            field=models.TextField(blank=True, help_text='Error message if Zoom registration failed'),
        ),
    ]
