# Generated by Django 5.2.1 on 2025-06-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0009_attendee_zoom_join_url_attendee_zoom_registered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='zoom_invite_link',
            field=models.URLField(blank=True, help_text='Meeting invite link for this attendee', max_length=500),
        ),
    ]
