# Generated by Django 5.2.1 on 2025-06-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0010_attendee_zoom_invite_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinardate',
            name='on_demand',
            field=models.BooleanField(default=False, help_text='Whether this is an on-demand webinar (no live date)'),
        ),
    ]
