# Generated by Django 5.2.1 on 2025-06-05 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0011_webinardate_on_demand'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnDemandAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('activation_sent_at', models.DateTimeField(blank=True, help_text='When the Kajabi grant offer activation was sent', null=True)),
                ('activation_success', models.BooleanField(blank=True, help_text='Whether the activation was successful', null=True)),
                ('activation_error', models.TextField(blank=True, help_text='Error message if activation failed')),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webinars.webinar')),
            ],
            options={
                'unique_together': {('webinar', 'email')},
            },
        ),
    ]
