# Generated by Django 5.2.1 on 2025-06-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0012_ondemandattendee'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='organization',
            field=models.CharField(blank=True, help_text='Organization name', max_length=255),
        ),
        migrations.AddField(
            model_name='attendee',
            name='salesforce_account_id',
            field=models.CharField(blank=True, help_text='Salesforce Account ID', max_length=50),
        ),
        migrations.AddField(
            model_name='attendee',
            name='salesforce_contact_id',
            field=models.CharField(blank=True, help_text='Salesforce Contact ID', max_length=50),
        ),
        migrations.AddField(
            model_name='attendee',
            name='salesforce_sync_error',
            field=models.TextField(blank=True, help_text='Error message if Salesforce sync failed'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='salesforce_sync_pending',
            field=models.BooleanField(default=True, help_text='Whether this attendee needs to be synced to Salesforce'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='salesforce_synced_at',
            field=models.DateTimeField(blank=True, help_text='When successfully synced to Salesforce', null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='salesforce_task_id',
            field=models.CharField(blank=True, help_text='Salesforce Task ID', max_length=50),
        ),
        migrations.AddField(
            model_name='bundleattendee',
            name='organization',
            field=models.CharField(blank=True, help_text='Organization name', max_length=255),
        ),
        migrations.AddField(
            model_name='bundleattendee',
            name='salesforce_account_id',
            field=models.CharField(blank=True, help_text='Salesforce Account ID', max_length=50),
        ),
        migrations.AddField(
            model_name='bundleattendee',
            name='salesforce_contact_id',
            field=models.CharField(blank=True, help_text='Salesforce Contact ID', max_length=50),
        ),
        migrations.AddField(
            model_name='bundleattendee',
            name='salesforce_sync_error',
            field=models.TextField(blank=True, help_text='Error message if Salesforce sync failed'),
        ),
        migrations.AddField(
            model_name='bundleattendee',
            name='salesforce_sync_pending',
            field=models.BooleanField(default=True, help_text='Whether this attendee needs to be synced to Salesforce'),
        ),
        migrations.AddField(
            model_name='bundleattendee',
            name='salesforce_synced_at',
            field=models.DateTimeField(blank=True, help_text='When successfully synced to Salesforce', null=True),
        ),
        migrations.AddField(
            model_name='bundleattendee',
            name='salesforce_task_id',
            field=models.CharField(blank=True, help_text='Salesforce Task ID', max_length=50),
        ),
        migrations.AddField(
            model_name='ondemandattendee',
            name='organization',
            field=models.CharField(blank=True, help_text='Organization name', max_length=255),
        ),
        migrations.AddField(
            model_name='ondemandattendee',
            name='salesforce_account_id',
            field=models.CharField(blank=True, help_text='Salesforce Account ID', max_length=50),
        ),
        migrations.AddField(
            model_name='ondemandattendee',
            name='salesforce_contact_id',
            field=models.CharField(blank=True, help_text='Salesforce Contact ID', max_length=50),
        ),
        migrations.AddField(
            model_name='ondemandattendee',
            name='salesforce_sync_error',
            field=models.TextField(blank=True, help_text='Error message if Salesforce sync failed'),
        ),
        migrations.AddField(
            model_name='ondemandattendee',
            name='salesforce_sync_pending',
            field=models.BooleanField(default=True, help_text='Whether this attendee needs to be synced to Salesforce'),
        ),
        migrations.AddField(
            model_name='ondemandattendee',
            name='salesforce_synced_at',
            field=models.DateTimeField(blank=True, help_text='When successfully synced to Salesforce', null=True),
        ),
        migrations.AddField(
            model_name='ondemandattendee',
            name='salesforce_task_id',
            field=models.CharField(blank=True, help_text='Salesforce Task ID', max_length=50),
        ),
    ]
